# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "2048"
  end
  config.vm.provision "shell",
	      inline:  "sudo mkdir -p /root/.ssh; sudo chmod 700 /root/.ssh; sudo bash -c 'echo \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwtaykCJc8HMxLE7V8Ka1tXMbjUqPj/vLRvLksioSuPxbqq5nKdjud9gZrj7Hv5zFrkyCnxMP9MF7B58wSaofBsl3fkiM0BEdiUEp3ls3RZLu4MVms6125YhN8XuJcL7tBzEsrE3AsxC9MT0uu+Hw+g+hmsEvXmt2Rf40D5Zoo297Zbp1MiXL7NIVnR9w7Day6DJmojree7RAS7PY2zRdUoqp5U9XYBXqqieZpDRanNj1C5Hi3UIctBnatfXzn1/gx7w3sfTEzCXidHbq6yORdLttRTf04+RvAd7FpS8GGXFNvJB5ToiyvmAJkfUVr/LYwPfu3HrwD60lWwZw1djcb\" > ~/.ssh/authorized_keys;chmod 600 ~/.ssh/authorized_keys'"
  config.vm.provision "shell", path: "../bin/provision.sh"
  config.vm.hostname = "formlogic"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.synced_folder "..", "/formlogic"
  config.ssh.forward_agent = true
end
