WellFormedFormula = Quantifiers '{' WellFormedFormula '}' | Disjunction
Quantifiers = Quantifiers Quantifier | Quantifier | epsilon
Quantifier = FOREACH LITERAL | EXISTS LITERAL
Disjunction = Disjunction <'||'> Conjunction | Conjunction
Conjunction = Conjunction <'&&'> Implication | Implication
Implication = Implication <'=>'> Term | Term
Negation = '~' Term
Term = <'('> WellFormedFormula <')'> | Negation | Predicate | LITERAL
Predicate = PRED '(' Arguments ')'
Arguments = Arguments ',' Argument | Argument
Argument = LITERAL | Predicate

LITERAL = #'[a-z]+'
PRED = #'[A-Z][a-z]*'
FOREACH = #'\\A'
EXISTS = #'\\E'
